/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;
import org.hibernate.Session;
public class App {
    public String getGreeting() {
        return "Hello world.";
    } 
    public static void main(String[] args){
        System.out.println(new App().getGreeting());
       
        Employee e1=new Employee();
        e1.setName("rajes");
        e1.setSalary(51000);
        e1.setDesigntion("Employee");
         Address a1=new Address();
         Address a2=new Address();
         a1.setCity("surat");
         a1.setEmployee(e1);
         a1.setNumber(234);
         a1.setState("gujarat");
         
         a2.setCity("ahemdabad");
         a2.setEmployee(e1);
         a2.setNumber(654);
         a2.setState("gujarat");
         
         
         
        //e1.setEid(1);       
    //    EntityManagerFactory emf=Persistence.createEntityManagerFactory("PERSISTENCE_UNIT_NAME");
    //    EntityManager em=emf.createEntityManager();
      //  em.getTransaction().begin();
        //em.persist(e1);
        //em.getTransaction().commit();
       // em.close();
       // emf.close();   
        Phone p=new Phone(93844493);      
       e1.setPid(p);
        Session s= HibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        s.save(e1);
        s.save(a1);
        s.save(a2);
        s.getTransaction().commit();        
        s.close();
       
    }
}
